
package com.gwm.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-22T08:37:48.468+08:00
 * Generated source version: 3.1.8
 * 
 */
public final class Service1Soap_Service1Soap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Service1");

    private Service1Soap_Service1Soap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Service1.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service1 ss = new Service1(wsdlURL, SERVICE_NAME);
        Service1Soap port = ss.getService1Soap12();  
        
        {
        System.out.println("Invoking parseXml...");
        java.lang.String _parseXml_xml = "";
        java.lang.String _parseXml__return = port.parseXml(_parseXml_xml);
        System.out.println("parseXml.result=" + _parseXml__return);


        }

        System.exit(0);
    }

}
